name: blast_docking
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11

  # --- Bioinformatique / BLAST ---
  - blast
  - biopython

  # --- Manipulation de données ---
  - pandas
  - requests
  - openpyxl
  - certifi
  - numpy

  # --- Docking moléculaire ---
  - autodock-vina
  - meeko
  - rdkit
  - openbabel

  # --- Visualisation (optionnel mais recommandé) ---
  - pymol-open-source