[project]
name = "docking-project"
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[dependencies]
python = "3.10.*"
pip = ">=25.3,<26"
rdkit = ">=2025.9.4,<2026"
scipy = ">=1.15.2,<2"
gemmi = ">=0.7.4,<0.8"
prody = ">=2.5.0,<3"
pandas = ">=2.3.3,<3"
statsmodels = ">=0.14.6,<0.15"
scikit-learn = ">=1.7.2,<2"
adjusttext = ">=1.3.0,<2"
seaborn = ">=0.13.2,<0.14"
plip = ">=3.0.0,<4"
jupyterlab = ">=4.5.1,<5"
ipykernel = ">=7.1.0,<8"
